import { Product } from './types';

/**
 * Datos de demostración. Se usan automáticamente cuando no hay variables de
 * entorno de Supabase configuradas, para que el sitio sea funcional desde el
 * día uno. En cuanto agregues NEXT_PUBLIC_SUPABASE_URL/ANON_KEY, lib/queries
 * pasa a leer productos reales desde la base de datos.
 */
const RAW_MOCK_PRODUCTS: Omit<Product, 'is_active' | 'ml_product_id' | 'rrss_status'>[] = [
  {
    id: '1',
    slug: 'iphone-13-128gb',
    name: 'iPhone 13 128GB',
    brand: 'Apple',
    category: 'celulares',
    price: 449990,
    original_price: 529990,
    image_url: 'https://picsum.photos/seed/iphone13/600/600',
    affiliate_url: '#',
    description:
      'iPhone 13 con chip A15 Bionic, cámara dual de 12MP y pantalla Super Retina XDR de 6.1".',
    specs: { Pantalla: '6.1"', Almacenamiento: '128', RAM: '4', Batería: '3240' },
    seller_reputation: 'verde',
    seller_sales_count: 4200,
    is_featured: true,
    created_at: '2026-08-01T00:00:00.000Z',
  },
  {
    id: '2',
    slug: 'samsung-galaxy-s23-256gb',
    name: 'Samsung Galaxy S23 256GB',
    brand: 'Samsung',
    category: 'celulares',
    price: 419990,
    original_price: 469990,
    image_url: 'https://picsum.photos/seed/galaxys23/600/600',
    affiliate_url: '#',
    description:
      'Galaxy S23 con Snapdragon 8 Gen 2, triple cámara de 50MP y pantalla Dynamic AMOLED 2X.',
    specs: { Pantalla: '6.1"', Almacenamiento: '256', RAM: '8', Batería: '3900' },
    seller_reputation: 'verde',
    seller_sales_count: 3100,
    is_featured: true,
    created_at: '2026-08-01T00:00:00.000Z',
  },
  {
    id: '3',
    slug: 'notebook-lenovo-ideapad-3',
    name: 'Notebook Lenovo IdeaPad 3 Ryzen 5',
    brand: 'Lenovo',
    category: 'computacion',
    price: 379990,
    original_price: 429990,
    image_url: 'https://picsum.photos/seed/ideapad3/600/600',
    affiliate_url: '#',
    description:
      'Notebook con AMD Ryzen 5, 8GB RAM, 512GB SSD y pantalla Full HD de 15.6".',
    specs: { Procesador: 'Ryzen 5', RAM: '8', Almacenamiento: '512', Pantalla: '15.6"' },
    seller_reputation: 'verde',
    seller_sales_count: 1850,
    is_featured: true,
    created_at: '2026-08-02T00:00:00.000Z',
  },
  {
    id: '4',
    slug: 'audifonos-sony-wh-1000xm4',
    name: 'Audífonos Sony WH-1000XM4',
    brand: 'Sony',
    category: 'electronica',
    price: 199990,
    original_price: 249990,
    image_url: 'https://picsum.photos/seed/sonyxm4/600/600',
    affiliate_url: '#',
    description:
      'Audífonos inalámbricos con cancelación de ruido líder en su categoría y hasta 30h de batería.',
    specs: { Batería: '30', Bluetooth: '5.0', Peso: '254' },
    seller_reputation: 'verde',
    seller_sales_count: 5400,
    is_featured: false,
    created_at: '2026-08-03T00:00:00.000Z',
  },
  {
    id: '5',
    slug: 'smart-tv-lg-55-4k',
    name: 'Smart TV LG 55" 4K UHD',
    brand: 'LG',
    category: 'electronica',
    price: 389990,
    original_price: 459990,
    image_url: 'https://picsum.photos/seed/lgtv55/600/600',
    affiliate_url: '#',
    description: 'Smart TV 4K con procesador Quad Core, HDR10 y webOS.',
    specs: { Pantalla: '55"', Resolución: '4K', HDMI: '3' },
    seller_reputation: 'verde',
    seller_sales_count: 980,
    is_featured: true,
    created_at: '2026-08-03T00:00:00.000Z',
  },
  {
    id: '6',
    slug: 'aspiradora-robot-xiaomi',
    name: 'Aspiradora Robot Xiaomi Robot Vacuum',
    brand: 'Xiaomi',
    category: 'hogar',
    price: 249990,
    original_price: 299990,
    image_url: 'https://picsum.photos/seed/xiaomivac/600/600',
    affiliate_url: '#',
    description: 'Robot aspiradora con mapeo láser y control desde app.',
    specs: { Autonomía: '150', Succión: '2100', Depósito: '0.45' },
    seller_reputation: 'verde',
    seller_sales_count: 760,
    is_featured: false,
    created_at: '2026-08-04T00:00:00.000Z',
  },
  {
    id: '7',
    slug: 'refrigerador-samsung-no-frost-410l',
    name: 'Refrigerador Samsung No Frost 410L',
    brand: 'Samsung',
    category: 'electrodomesticos',
    price: 549990,
    original_price: 629990,
    image_url: 'https://picsum.photos/seed/samsungfridge/600/600',
    affiliate_url: '#',
    description: 'Refrigerador No Frost de dos puertas con dispensador de agua.',
    specs: { Capacidad: '410', Tipo: 'No Frost', Puertas: '2' },
    seller_reputation: 'verde',
    seller_sales_count: 430,
    is_featured: false,
    created_at: '2026-08-05T00:00:00.000Z',
  },
  {
    id: '8',
    slug: 'notebook-macbook-air-m1',
    name: 'MacBook Air M1 256GB',
    brand: 'Apple',
    category: 'computacion',
    price: 699990,
    original_price: 799990,
    image_url: 'https://picsum.photos/seed/macbookair/600/600',
    affiliate_url: '#',
    description: 'MacBook Air con chip M1, 8GB RAM unificada y hasta 18h de batería.',
    specs: { Procesador: 'Apple M1', RAM: '8', Almacenamiento: '256', Pantalla: '13.3"' },
    seller_reputation: 'verde',
    seller_sales_count: 2200,
    is_featured: true,
    created_at: '2026-08-05T00:00:00.000Z',
  },
];

export const MOCK_PRODUCTS: Product[] = RAW_MOCK_PRODUCTS.map((p) => ({
  ...p,
  is_active: true,
  ml_product_id: null,
  rrss_status: 'sin_usar',
}));
